# Generated by Django 5.2.16 on 2026-07-16 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("text", models.TextField(verbose_name="question text")),
                ("order", models.PositiveSmallIntegerField(verbose_name="order")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
            ],
            options={
                "verbose_name": "question",
                "verbose_name_plural": "questions",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="AnswerOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("text", models.CharField(max_length=500, verbose_name="option text")),
                ("order", models.PositiveSmallIntegerField(verbose_name="order")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="polls.question",
                        verbose_name="question",
                    ),
                ),
            ],
            options={
                "verbose_name": "answer option",
                "verbose_name_plural": "answer options",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_surveys",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
            ],
            options={
                "verbose_name": "survey",
                "verbose_name_plural": "surveys",
            },
        ),
        migrations.AddField(
            model_name="question",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="polls.survey",
                verbose_name="survey",
            ),
        ),
        migrations.CreateModel(
            name="SurveyAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("started", "Started"), ("completed", "Completed")],
                        default="started",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True, verbose_name="started at")),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="completed at"),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="polls.survey",
                        verbose_name="survey",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="survey_attempts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "survey attempt",
                "verbose_name_plural": "survey attempts",
            },
        ),
        migrations.CreateModel(
            name="UserAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "time_spent_ms",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="time spent, ms"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="polls.surveyattempt",
                        verbose_name="attempt",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="answers",
                        to="polls.answeroption",
                        verbose_name="answer option",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="answers",
                        to="polls.question",
                        verbose_name="question",
                    ),
                ),
            ],
            options={
                "verbose_name": "user answer",
                "verbose_name_plural": "user answers",
            },
        ),
        migrations.AddIndex(
            model_name="answeroption",
            index=models.Index(fields=["question", "order"], name="option_question_order_idx"),
        ),
        migrations.AddConstraint(
            model_name="answeroption",
            constraint=models.UniqueConstraint(
                fields=("question", "order"), name="uniq_option_order"
            ),
        ),
        migrations.AddIndex(
            model_name="survey",
            index=models.Index(fields=["status", "created_at"], name="survey_status_created_idx"),
        ),
        migrations.AddIndex(
            model_name="survey",
            index=models.Index(fields=["author", "created_at"], name="survey_author_created_idx"),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["survey", "order"], name="question_survey_order_idx"),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.UniqueConstraint(
                fields=("survey", "order"), name="uniq_question_order"
            ),
        ),
        migrations.AddIndex(
            model_name="surveyattempt",
            index=models.Index(fields=["user", "status"], name="attempt_user_status_idx"),
        ),
        migrations.AddIndex(
            model_name="surveyattempt",
            index=models.Index(fields=["survey", "status"], name="attempt_survey_status_idx"),
        ),
        migrations.AddIndex(
            model_name="surveyattempt",
            index=models.Index(fields=["survey", "completed_at"], name="attempt_survey_done_idx"),
        ),
        migrations.AddConstraint(
            model_name="surveyattempt",
            constraint=models.UniqueConstraint(
                fields=("survey", "user"), name="uniq_survey_attempt_user"
            ),
        ),
        migrations.AddIndex(
            model_name="useranswer",
            index=models.Index(fields=["question", "option"], name="answer_question_option_idx"),
        ),
        migrations.AddIndex(
            model_name="useranswer",
            index=models.Index(fields=["attempt", "created_at"], name="answer_attempt_created_idx"),
        ),
        migrations.AddConstraint(
            model_name="useranswer",
            constraint=models.UniqueConstraint(
                fields=("attempt", "question"), name="uniq_answer_question"
            ),
        ),
    ]
